// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlszZb4yWTfX-pPzvhM4wK126kxyHLkd4',
    appId: '1:952449598956:web:ec697bbf14c3ccf6276cc9',
    messagingSenderId: '952449598956',
    projectId: 'yt-clone-edb8c',
    authDomain: 'yt-clone-edb8c.firebaseapp.com',
    storageBucket: 'yt-clone-edb8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFk-ftmjWb5_X5nwX6JRWA2K1qTlfhJuo',
    appId: '1:952449598956:android:43800bc947b2905c276cc9',
    messagingSenderId: '952449598956',
    projectId: 'yt-clone-edb8c',
    storageBucket: 'yt-clone-edb8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwXhBj-hLHKr1DMpIeBZiM8M04EZsg0q0',
    appId: '1:952449598956:ios:8e07a710099778fe276cc9',
    messagingSenderId: '952449598956',
    projectId: 'yt-clone-edb8c',
    storageBucket: 'yt-clone-edb8c.appspot.com',
    iosBundleId: 'com.example.ytclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwXhBj-hLHKr1DMpIeBZiM8M04EZsg0q0',
    appId: '1:952449598956:ios:8e07a710099778fe276cc9',
    messagingSenderId: '952449598956',
    projectId: 'yt-clone-edb8c',
    storageBucket: 'yt-clone-edb8c.appspot.com',
    iosBundleId: 'com.example.ytclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlszZb4yWTfX-pPzvhM4wK126kxyHLkd4',
    appId: '1:952449598956:web:279ca781aafb5795276cc9',
    messagingSenderId: '952449598956',
    projectId: 'yt-clone-edb8c',
    authDomain: 'yt-clone-edb8c.firebaseapp.com',
    storageBucket: 'yt-clone-edb8c.appspot.com',
  );

}